updated comment
Zilliqa/marketplace-contracts pull request #44
Opened 2022-06-21 06:32 UTC by narendra-zil

2022-06-21 07:29 UTC, anton-trunov approved these changes

2022-06-22 03:01 UTC, inamirandaz approved these changes

2022-06-22 03:01 UTC, inamirandaz commented
@frankmeds what is the error here?

2022-06-22 03:05 UTC, inamirandaz requested changes
@narendra-zil please fix the broken links here (included in the comment of Igor)
lines 197, 210, 222 broken links

2022-06-22 05:42 UTC, narendra-zil commented
> @narendra-zil please fix the broken links here (included in the comment of Igor) lines 197, 210, 222 broken links

fixed the broken links on lines you mentioned.

2022-06-27 16:04 UTC, merged